//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueensBakery_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bakery_Desserts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bakery_Desserts()
        {
            this.Client_Order = new HashSet<Client_Order>();
        }
    
        public string Dessert_id { get; set; }
        public string Dessert_description { get; set; }
        public string Dessert_type { get; set; }
        public string Dessert_category { get; set; }
        public string ID_promo_disc { get; set; }
        public decimal Dessert_Unit_price { get; set; }
    
        public virtual Promos_discounts Promos_discounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Order> Client_Order { get; set; }
    }
}
