//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueensBakery_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bakery_clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bakery_clients()
        {
            this.Client_Order = new HashSet<Client_Order>();
        }
    
        public string Client_ID { get; set; }
        public string Client_name { get; set; }
        public Nullable<System.DateTime> Client_birth { get; set; }
        public int Client_age { get; set; }
        public string Client_genre { get; set; }
        public string Client_phone { get; set; }
        public string Client_address { get; set; }
        public string ID_promo_desc { get; set; }
    
        public virtual Promos_discounts Promos_discounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Order> Client_Order { get; set; }
    }
}
