//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueensBakery_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Bill
    {
        public string Bill_Code { get; set; }
        public int Bill_orderNum { get; set; }
        public string Payment_methods { get; set; }
        public string ID_promo_disc { get; set; }
        public Nullable<System.DateTime> Bill_date { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Sales_taxes { get; set; }
        public decimal Total { get; set; }
        public string Client_ID { get; set; }
    
        public virtual payment_methods payment_methods1 { get; set; }
        public virtual Promos_discounts Promos_discounts { get; set; }
        public virtual Client_Order Client_Order { get; set; }
    }
}
