//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueensBakery_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QueensBakeryEntities : DbContext
    {
        public QueensBakeryEntities()
            : base("name=QueensBakeryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bakery_clients> Bakery_clients { get; set; }
        public virtual DbSet<Bakery_Desserts> Bakery_Desserts { get; set; }
        public virtual DbSet<Bakery_Drinks> Bakery_Drinks { get; set; }
        public virtual DbSet<Client_Bill> Client_Bill { get; set; }
        public virtual DbSet<Client_Order> Client_Order { get; set; }
        public virtual DbSet<payment_methods> payment_methods { get; set; }
        public virtual DbSet<Promos_discounts> Promos_discounts { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Users_Bakery> Users_Bakerye { get; set; }
    }
}
