//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueensBakery_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promos_discounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promos_discounts()
        {
            this.Bakery_clients = new HashSet<Bakery_clients>();
            this.Bakery_Desserts = new HashSet<Bakery_Desserts>();
            this.Bakery_Drinks = new HashSet<Bakery_Drinks>();
            this.Client_Bill = new HashSet<Client_Bill>();
        }
    
        public string ID_promo { get; set; }
        public Nullable<decimal> PD_Percentage { get; set; }
        public string Descript { get; set; }
        public System.DateTime start_d { get; set; }
        public System.DateTime End_d { get; set; }
        public string PD_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bakery_clients> Bakery_clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bakery_Desserts> Bakery_Desserts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bakery_Drinks> Bakery_Drinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Bill> Client_Bill { get; set; }
    }
}
