//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueensBakery_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Bakery
    {
        public string User_code { get; set; }
        public string User_password { get; set; }
        public string User_ID { get; set; }
        public string User_name { get; set; }
        public string User_genre { get; set; }
        public string User_email { get; set; }
        public string User_phone { get; set; }
        public string Rol_ID { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
